### ISSUE TITLE
Naming convention for MPI exercises

### ISSUE THREAD

**Issue by svretina** [carstenbauer/JuliaHLRS24#2]
the `neighbors` variable in the diffusion exercise `2_diffusion_2d_mpi` has keywords `top` and `bottom` and in the `3_diffusion_2d_mpi_gpu` exercise the instructions suggest to copy the `update_halo!` function from the aforementioned file but the `neighbors` variable now has `up` and `down` keywords. This will cause an error.

**Comment by carstenbauer** [comment]
Fixed.
